// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgqBP7z26uDa1Fce49G6OZA6FYF0Kfz2k',
    appId: '1:30219884796:web:fecf57502e34484d609f79',
    messagingSenderId: '30219884796',
    projectId: 'travix-30cc2',
    authDomain: 'travix-30cc2.firebaseapp.com',
    storageBucket: 'travix-30cc2.firebasestorage.app',
    measurementId: 'G-G4LE159HLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQSYdaP1_qIP-IRjW8Mq-Gjv6ubdrAQmE',
    appId: '1:30219884796:android:29c817e72ec0d60e609f79',
    messagingSenderId: '30219884796',
    projectId: 'travix-30cc2',
    storageBucket: 'travix-30cc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa94uPNPSmAKoGMX6yD2piQOZkJkzrOgU',
    appId: '1:30219884796:ios:9f6738418f75dc31609f79',
    messagingSenderId: '30219884796',
    projectId: 'travix-30cc2',
    storageBucket: 'travix-30cc2.firebasestorage.app',
    iosBundleId: 'com.example.travix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa94uPNPSmAKoGMX6yD2piQOZkJkzrOgU',
    appId: '1:30219884796:ios:9f6738418f75dc31609f79',
    messagingSenderId: '30219884796',
    projectId: 'travix-30cc2',
    storageBucket: 'travix-30cc2.firebasestorage.app',
    iosBundleId: 'com.example.travix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgqBP7z26uDa1Fce49G6OZA6FYF0Kfz2k',
    appId: '1:30219884796:web:279c7fef90a344b0609f79',
    messagingSenderId: '30219884796',
    projectId: 'travix-30cc2',
    authDomain: 'travix-30cc2.firebaseapp.com',
    storageBucket: 'travix-30cc2.firebasestorage.app',
    measurementId: 'G-GB3KGKB2VV',
  );
}
